version: '3'
services:
  sut:
    build: .
    command: bash ./scripts/run_tests_and_linter.sh
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=test
      - REDIS_HOST=redis
      - SLACK_API_TOKEN=xoxp-00000000000
    depends_on:
      - redis
  redis:
    image: redis
