version: '3'
services:
  app:
    build: .
    command: bash
    env_file: variables.env
    environment:
      - BOOKING_DURATION=20
      - LOG_LEVEL=debug
      - NODE_ENV=development
      - REDIS_HOST=redis
      - TZ=Europe/London
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  redis_data:
